version: '3.3'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: database-test.cdqsrkknxl2e.ap-northeast-2.rds.amazonaws.com
