apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: efs-app
  namespace: default
spec:
  selector:
    matchLabels:
      name: efs-app
  template:
    metadata:
      labels:
        name: efs-app
    spec:
      containers:
      - name: app
        image: DOCKER_REGISTRY/APP_NAME:CI_PIPELINE_IID
        ports:
         - containerPort: 80
        volumeMounts:
         - name: persistent-storage
           mountPath: data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
